name: graphunzip-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.12
  #- bioconda::minimap2
  - numpy
  - scipy
  - zlib
  - matplotlib
  - pandas
  - htslib
  #- graphaligner
  #- spades
  - pip
  - pip:
      - biopython
      - pysam
      - black
      - setuptools_scm
      - build
      - twine
